webhook:
  enabled: true
  url: "PUT_WEBHOOK_URL_HERE"
  timeout-ms: 5000
  override-username: true
  username-prefix: ""  # chat username prefix, e.g. "[MC] "
  # Use tokens <uuid> and <player>.
  # Defaults use Minotar for reliability. You can switch to Crafatar easily.
  avatar-url-template: "https://minotar.net/avatar/<uuid>/128"
  avatar-fallback-url: "https://minotar.net/avatar/Steve/128"
  check-avatar: true
  # Tokens: <player>, <message>
  content-template: "<message>"

server-events:
  enabled: true
  username-prefix: "(Server) "
  join:
    enabled: true
    # Tokens: <player>
    content-template: "<player> joined"
  quit:
    enabled: true
    # Tokens: <player>
    content-template: "<player> left"

messages:
  reload-success: "<green>fendoris-discordhook reloaded.</green>"
  reload-fail: "Error in language string."
  no-permission: "<red>You do not have permission.</red>"
  webhook-missing: "<red>Webhook is missing or disabled. Check config.yml.</red>"
